### ISSUE TITLE
UTF-8 encoding seem to be broken

### ISSUE THREAD

**Issue by tuscland** [mdedetrich/java-premailer-wrapper#1]
Hi!

I can't seem to be able to process valid UTF-8 strings, it always get converted to a wrong ASCII representation.

For example, if I enter the string `&#x1F604;` (which is the entity encoding for a emoji smiley), the result is `&#xd83d;&#xde04;`. I don't know why entities are interpreted along the way, but it definitely looks like an encoding problem between the Java and Ruby interfaces.

Best,
Cam

**Comment by tuscland** [comment]
OK, so it looked like an issue with Java itself as described [in this article](http://www.jillesvangurp.com/2013/06/14/jruby-utf-8/). But the problem I have is more related to [an issue with nokigiri running on JRUby as described in this article](http://blog.rayapps.com/2013/03/11/7-things-that-can-go-wrong-with-ruby-19-string-encodings/).

**Comment by mdedetrich** [comment]
What system are you running on (according to http://www.jillesvangurp.com/2013/06/14/jruby-utf-8/ which you posted earlier, different systems may apply a different encoding).

I will look into it next week, happy to accept a pull request fixing the issue (tbh I am not completely familiar with JRuby personally, I created this project because I needed to use premailer on the JVM, in my case I predominantly work with Scala)

**Comment by tuscland** [comment]
My system is OS X, unfortunately none of the solutions found so far worked.
I will continue to investigate...

**Comment by tuscland** [comment]
Just tried the latest update, and it seems the problem is gone.
Thanks!
